//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrpcBindServer
{
    using Microsoft.AspNetCore.Builder;
    using Grpc.Core;
    using SoftBand.EntityManager;
    
    
    public partial class GrpcBindService
    {
        
        public static Server Server { get; set; }
        
        public static void UseEndpoints(Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints)
        {
            endpoints.MapGrpcService<com.example.ExampleServiceService>();
        }
    }
}
