//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrpcServices
{
    using System;
    using System.Threading.Tasks;
    using Microsoft.Extensions.DependencyInjection;
    
    
    public partial class Startup
    {
        
        public static void ConfigureServices(IServiceCollection services)
        {
            services.AddGrpc(options =>
            {
                //If true, detailed exception messages are returned to clients when an exception is thrown
                //in a service method. The default is false. Setting EnableDetailedErrors to true can leak
                //sensitive information.
                //https://docs.microsoft.com/ko-kr/aspnet/core/grpc/security?view=aspnetcore-5.0
                options.EnableDetailedErrors = true;
                
                //The maximum message size in bytes that can be received by the server. If the server
                //receives a message that exceeds this limit, it throws an exception. Increasing this value
                //allows the server to receive larger messages, but can negatively impact memory consumption.
                //When set to null, the message size is unlimited.
                options.MaxReceiveMessageSize = 2 * 1024 * 1024; // 2 MB
                
                //The maximum message size in bytes that can be sent from the server. Attempting to
                //send a message that exceeds the configured maximum message size results in an exception.
                //When set to null, the message size is unlimited.
                options.MaxSendMessageSize = 5 * 1024 * 1024; // 5 MB
            });
        }
    }
}
